/*
  クラフトクエスト
    QID: bjs:GSQ_breeds:make:(Material):(Material2):(mate..),(個数1):(G-EXP報酬1),(個数数2):(G-EXP報酬2), ...
    QID: bjs:GSQ_breeds:make:(reg:MaterialName),(個数1):(G-EXP報酬1),(個数数2):(G-EXP報酬2), ...

  (注)
    サーバー側のプレイヤー統計が有効になってる必要がある
*/

// 表示名
DISPLAY_LINE = "{item}を{count}クラフトする";


/*
  ここから実装
*/
var Bukkit = Java.type("org.bukkit.Bukkit");
var Material = Java.type("org.bukkit.Material");
var Statistic = Java.type("org.bukkit.Statistic");

var quests = [];
function createQuest(api) {
    return {
        guild: api.guild,
        api: api,
        config: api.config,
        args: api.arguments,
        objectives: null,
        targetItems: null,
    };
}
function getGuild(api) {  for (idx in quests) { if (quests[idx].api === api) return quests[idx].guild; }  }
function getQuest(api) {  for (idx in quests) { if (quests[idx].api === api) return quests[idx] }  }
function getQuestsByMember(memberId) { return quests.filter(function (q) { return q.guild.isJoined(memberId); }); }
function make(clazz, guild, args) {
    return Java.extend(Java.type(clazz), {
        onLoad: function(api) {  var q = createQuest(api); quests.push(q); onLoad(api, q);  },
        onUnload: function(api) {  try {onUnload(api, getQuest(api))}catch(err){}; quests = quests.filter(function(q) { return q.api !== api });  },
        getReward: function(api) {  return getReward(getQuest(api));  },
        getMaxTier: function(api) {  return getQuest(api).objectives.length; },
        getCurrentTier: function(api) {  return getCompletedTier(getQuest(api));  },
        getDisplayName: function(api) {  return getDisplayName(getQuest(api));  },
        getProgressValue: function(api) {  return getCurrentCount(getQuest(api));  },
        getProgressMaxValue: function(api) {  return getNextCount(getQuest(api));  },
        getConfigId: function(api) {  return api.functionKey.scriptName + "-" + args[0];  },
    });
}

function getDisplayName(quest) {
    var nextCount = getNextCount(quest, getCompletedTier(quest));
    var amount = (nextCount % 64) + "個";
    if (nextCount >= 64) {
        amount = Math.floor(nextCount / 64) + "スタック" + ((nextCount % 64 >= 1) ? "と" + amount : "");
    }

    var targetItems = quest.targetItems;
    return DISPLAY_LINE
        .replace("{count}", amount)
        .replace("{item}", ((targetItems.length == 1) ? ITEM_NAMES[targetItems[0].name()] : "特定のアイテム"));
}

function getCurrentCount(quest) {
    return quest.config.getInt("count", 0);
}

function setCurrentCount(quest, count) {
    quest.config.set("count", count);
}

function getNextCount(quest) {
    var objective = quest.objectives[getCompletedTier(quest)];
    return (objective) ? objective.count : null;
}

function getCompletedTier(quest) {
    return quest.config.getInt("tier", 0);
}

function setTier(quest, tier) {
    quest.config.set("tier", tier);
    quest.config.save();
}

function getReward(quest) {
    var objective = quest.objectives[getCompletedTier(quest)];
    return (objective) ? objective.reward : 0;
}

function onLoad(api, quest) {
    if (api.arguments.length < 2)
        api.throwLoad("引数が足りません");

    var types = [];

    if (api.arguments[0].startsWith("reg:")) {
        var regex = api.arguments[0].substring(4);

        var materials = Material.values();
        for (idx in materials) {
            var m = materials[idx];
            if (m.name().match(regex) != null) {
                types.push(m);
            }
        }

        var size = types.length;
        log.info("Regex " + size + " material loaded");

    } else {
        api.arguments[0].split(":").forEach(function(typeName) {
            try {
                types.push(Material.valueOf(typeName));
            } catch (e) {
                api.throwLoad("アイテム " + typeName + " は無効です");
            }
        });
    }

    quest.targetItems = types;
    quest.objectives = [];

    for (idx in api.arguments) {
        if (idx == 0)
            continue;
        
        var objective = api.arguments[idx].split(":");
        var count = parseInt(objective[0]);
        var reward = parseInt(objective[1]);
        if (isNaN(count) || isNaN(reward))
            api.throwLoad("パラメータが正しくありません(idx:" + idx + "): " + api.arguments[idx]);
        
        quest.objectives.push({count: count, reward: reward});
    }
}

function onUnload(api, quest) {

}

function getIcon(api, icon) {
    var quest = getQuest(api);
    icon.icon = Material.CRAFTING_TABLE;
    icon.category = "crafts";
    return quest.targetItems;
}


/*
  utils
*/


/*
  listeners
*/
bjs.on("playerStatisticIncrement", function(event) {
    var player = event.player;
    if (Statistic.CRAFT_ITEM !== event.statistic)
        return;
    
    getQuestsByMember(player.uniqueId).forEach(function(quest) {
        if (quest.targetItems.indexOf(event.material) == -1)
            return;
        
        var config = quest.config;
        var api = quest.api;
        var tier = getCompletedTier(quest);
        var count = getCurrentCount(quest);
        count += Math.max(0, event.newValue - event.previousValue);

        var next = getNextCount(quest);

        setCurrentCount(quest, count);

        // 目標カウントを超えた and 現Tierが存在する (tier+1になった時に、そのTierが存在しなければ無視される)
        if (count >= next && quest.objectives[tier] != null) {
            api.updateTier(tier+1);

            config.set("tier", tier+1);
            config.save();
        }
    });
});


var ITEM_NAMES = {
    "STONE": "石",
    "GRANITE": "花崗岩",
    "POLISHED_GRANITE": "磨かれた花崗岩",
    "DIORITE": "閃緑岩",
    "POLISHED_DIORITE": "磨かれた閃緑岩",
    "ANDESITE": "安山岩",
    "POLISHED_ANDESITE": "磨かれた安山岩",
    "DEEPSLATE": "深層岩",
    "COBBLED_DEEPSLATE": "深層岩の丸石",
    "POLISHED_DEEPSLATE": "磨かれた深層岩",
    "CALCITE": "方解石",
    "TUFF": "凝灰岩",
    "DRIPSTONE_BLOCK": "鍾乳石ブロック",
    "GRASS_BLOCK": "草ブロック",
    "DIRT": "土",
    "COARSE_DIRT": "粗い土",
    "PODZOL": "ポドゾル",
    "ROOTED_DIRT": "根付いた土",
    "CRIMSON_NYLIUM": "真紅のナイリウム",
    "WARPED_NYLIUM": "歪んだナイリウム",
    "COBBLESTONE": "丸石",
    "OAK_PLANKS": "オークの板材",
    "SPRUCE_PLANKS": "トウヒの板材",
    "BIRCH_PLANKS": "シラカバの板材",
    "JUNGLE_PLANKS": "ジャングルの板材",
    "ACACIA_PLANKS": "アカシアの板材",
    "DARK_OAK_PLANKS": "ダークオークの板材",
    "CRIMSON_PLANKS": "真紅の板材",
    "WARPED_PLANKS": "歪んだ板材",
    "OAK_SAPLING": "オークの苗木",
    "SPRUCE_SAPLING": "トウヒの苗木",
    "BIRCH_SAPLING": "シラカバの苗木",
    "JUNGLE_SAPLING": "ジャングルの苗木",
    "ACACIA_SAPLING": "アカシアの苗木",
    "DARK_OAK_SAPLING": "ダークオークの苗木",
    "BEDROCK": "岩盤",
    "SAND": "砂",
    "RED_SAND": "赤い砂",
    "GRAVEL": "砂利",
    "COAL_ORE": "石炭鉱石",
    "DEEPSLATE_COAL_ORE": "深層石炭鉱石",
    "IRON_ORE": "鉄鉱石",
    "DEEPSLATE_IRON_ORE": "深層鉄鉱石",
    "COPPER_ORE": "銅鉱石",
    "DEEPSLATE_COPPER_ORE": "深層銅鉱石",
    "GOLD_ORE": "金鉱石",
    "DEEPSLATE_GOLD_ORE": "深層金鉱石",
    "REDSTONE_ORE": "レッドストーン鉱石",
    "DEEPSLATE_REDSTONE_ORE": "深層レッドストーン鉱石",
    "EMERALD_ORE": "エメラルド鉱石",
    "DEEPSLATE_EMERALD_ORE": "深層エメラルド鉱石",
    "LAPIS_ORE": "ラピスラズリ鉱石",
    "DEEPSLATE_LAPIS_ORE": "深層ラピスラズリ鉱石",
    "DIAMOND_ORE": "ダイヤモンド鉱石",
    "DEEPSLATE_DIAMOND_ORE": "深層ダイヤモンド鉱石",
    "NETHER_GOLD_ORE": "ネザー金鉱石",
    "NETHER_QUARTZ_ORE": "ネザークォーツ鉱石",
    "ANCIENT_DEBRIS": "古代の残骸",
    "COAL_BLOCK": "石炭ブロック",
    "RAW_IRON_BLOCK": "鉄の原石ブロック",
    "RAW_COPPER_BLOCK": "銅の原石ブロック",
    "RAW_GOLD_BLOCK": "金の原石ブロック",
    "AMETHYST_BLOCK": "アメジストブロック",
    "BUDDING_AMETHYST": "芽生えたアメジスト",
    "IRON_BLOCK": "鉄ブロック",
    "COPPER_BLOCK": "銅ブロック",
    "GOLD_BLOCK": "金ブロック",
    "DIAMOND_BLOCK": "ダイヤモンドブロック",
    "NETHERITE_BLOCK": "ネザライトブロック",
    "EXPOSED_COPPER": "風化した銅",
    "WEATHERED_COPPER": "錆びた銅",
    "OXIDIZED_COPPER": "酸化した銅",
    "CUT_COPPER": "切り込み入りの銅",
    "EXPOSED_CUT_COPPER": "風化した切り込み入りの銅",
    "WEATHERED_CUT_COPPER": "錆びた切り込み入りの銅",
    "OXIDIZED_CUT_COPPER": "酸化した切り込み入りの銅",
    "CUT_COPPER_STAIRS": "切り込み入りの銅の階段",
    "EXPOSED_CUT_COPPER_STAIRS": "風化した切り込み入りの銅の階段",
    "WEATHERED_CUT_COPPER_STAIRS": "錆びた切り込み入りの銅の階段",
    "OXIDIZED_CUT_COPPER_STAIRS": "酸化した切り込み入りの銅の階段",
    "CUT_COPPER_SLAB": "切り込み入りの銅のハーフブロック",
    "EXPOSED_CUT_COPPER_SLAB": "風化した切り込み入りの銅のハーフブロック",
    "WEATHERED_CUT_COPPER_SLAB": "錆びた切り込み入りの銅のハーフブロック",
    "OXIDIZED_CUT_COPPER_SLAB": "酸化した切り込み入りの銅のハーフブロック",
    "WAXED_COPPER_BLOCK": "錆止めされた銅ブロック",
    "WAXED_EXPOSED_COPPER": "錆止めされた風化した銅",
    "WAXED_WEATHERED_COPPER": "錆止めされた錆びた銅",
    "WAXED_OXIDIZED_COPPER": "錆止めされた酸化した銅",
    "WAXED_CUT_COPPER": "錆止めされた切り込み入りの銅",
    "WAXED_EXPOSED_CUT_COPPER": "錆止めされた風化した切り込み入りの銅",
    "WAXED_WEATHERED_CUT_COPPER": "錆止めされた錆びた切り込み入りの銅",
    "WAXED_OXIDIZED_CUT_COPPER": "錆止めされた酸化した切り込み入りの銅",
    "WAXED_CUT_COPPER_STAIRS": "錆止めされた切り込み入りの銅の階段",
    "WAXED_EXPOSED_CUT_COPPER_STAIRS": "錆止めされた風化した切り込み入りの銅の階段",
    "WAXED_WEATHERED_CUT_COPPER_STAIRS": "錆止めされた錆びた切り込み入りの銅の階段",
    "WAXED_OXIDIZED_CUT_COPPER_STAIRS": "錆止めされた酸化した切り込み入りの銅の階段",
    "WAXED_CUT_COPPER_SLAB": "錆止めされた切り込み入りの銅のハーフブロック",
    "WAXED_EXPOSED_CUT_COPPER_SLAB": "錆止めされた風化した切り込み入りの銅のハーフブロック",
    "WAXED_WEATHERED_CUT_COPPER_SLAB": "錆止めされた錆びた切り込み入りの銅のハーフブロック",
    "WAXED_OXIDIZED_CUT_COPPER_SLAB": "錆止めされた酸化した切り込み入りの銅のハーフブロック",
    "OAK_LOG": "オークの原木",
    "SPRUCE_LOG": "トウヒの原木",
    "BIRCH_LOG": "シラカバの原木",
    "JUNGLE_LOG": "ジャングルの原木",
    "ACACIA_LOG": "アカシアの原木",
    "DARK_OAK_LOG": "ダークオークの原木",
    "CRIMSON_STEM": "真紅の幹",
    "WARPED_STEM": "歪んだ幹",
    "STRIPPED_OAK_LOG": "樹皮を剥いだオークの原木",
    "STRIPPED_SPRUCE_LOG": "樹皮を剥いだトウヒの原木",
    "STRIPPED_BIRCH_LOG": "樹皮を剥いだシラカバの原木",
    "STRIPPED_JUNGLE_LOG": "樹皮を剥いだジャングルの原木",
    "STRIPPED_ACACIA_LOG": "樹皮を剥いだアカシアの原木",
    "STRIPPED_DARK_OAK_LOG": "樹皮を剥いだダークオークの原木",
    "STRIPPED_CRIMSON_STEM": "表皮を剥いだ真紅の幹",
    "STRIPPED_WARPED_STEM": "表皮を剥いだ歪んだ幹",
    "STRIPPED_OAK_WOOD": "樹皮を剥いだオークの木",
    "STRIPPED_SPRUCE_WOOD": "樹皮を剥いだトウヒの木",
    "STRIPPED_BIRCH_WOOD": "樹皮を剥いだシラカバの木",
    "STRIPPED_JUNGLE_WOOD": "樹皮を剥いだジャングルの木",
    "STRIPPED_ACACIA_WOOD": "樹皮を剥いだアカシアの木",
    "STRIPPED_DARK_OAK_WOOD": "樹皮を剥いだダークオークの木",
    "STRIPPED_CRIMSON_HYPHAE": "表皮を剥いだ真紅の菌糸",
    "STRIPPED_WARPED_HYPHAE": "表皮を剥いだ歪んだ菌糸",
    "OAK_WOOD": "オークの木",
    "SPRUCE_WOOD": "トウヒの木",
    "BIRCH_WOOD": "シラカバの木",
    "JUNGLE_WOOD": "ジャングルの木",
    "ACACIA_WOOD": "アカシアの木",
    "DARK_OAK_WOOD": "ダークオークの木",
    "CRIMSON_HYPHAE": "真紅の菌糸",
    "WARPED_HYPHAE": "歪んだ菌糸",
    "OAK_LEAVES": "オークの葉",
    "SPRUCE_LEAVES": "トウヒの葉",
    "BIRCH_LEAVES": "シラカバの葉",
    "JUNGLE_LEAVES": "ジャングルの葉",
    "ACACIA_LEAVES": "アカシアの葉",
    "DARK_OAK_LEAVES": "ダークオークの葉",
    "AZALEA_LEAVES": "ツツジの葉",
    "FLOWERING_AZALEA_LEAVES": "開花したツツジの葉",
    "SPONGE": "スポンジ",
    "WET_SPONGE": "濡れたスポンジ",
    "GLASS": "ガラス",
    "TINTED_GLASS": "遮光ガラス",
    "LAPIS_BLOCK": "ラピスラズリブロック",
    "SANDSTONE": "砂岩",
    "CHISELED_SANDSTONE": "模様入りの砂岩",
    "CUT_SANDSTONE": "研がれた砂岩",
    "COBWEB": "クモの巣",
    "GRASS": "草",
    "FERN": "シダ",
    "AZALEA": "ツツジ",
    "FLOWERING_AZALEA": "開花したツツジ",
    "DEAD_BUSH": "枯れ木",
    "SEAGRASS": "海草",
    "SEA_PICKLE": "シーピクルス",
    "WHITE_WOOL": "白色の羊毛",
    "ORANGE_WOOL": "橙色の羊毛",
    "MAGENTA_WOOL": "赤紫色の羊毛",
    "LIGHT_BLUE_WOOL": "空色の羊毛",
    "YELLOW_WOOL": "黄色の羊毛",
    "LIME_WOOL": "黄緑色の羊毛",
    "PINK_WOOL": "桃色の羊毛",
    "GRAY_WOOL": "灰色の羊毛",
    "LIGHT_GRAY_WOOL": "薄灰色の羊毛",
    "CYAN_WOOL": "青緑色の羊毛",
    "PURPLE_WOOL": "紫色の羊毛",
    "BLUE_WOOL": "青色の羊毛",
    "BROWN_WOOL": "茶色の羊毛",
    "GREEN_WOOL": "緑色の羊毛",
    "RED_WOOL": "赤色の羊毛",
    "BLACK_WOOL": "黒色の羊毛",
    "DANDELION": "タンポポ",
    "POPPY": "ポピー",
    "BLUE_ORCHID": "ヒスイラン",
    "ALLIUM": "アリウム",
    "AZURE_BLUET": "ヒナソウ",
    "RED_TULIP": "赤色のチューリップ",
    "ORANGE_TULIP": "橙色のチューリップ",
    "WHITE_TULIP": "白色のチューリップ",
    "PINK_TULIP": "桃色のチューリップ",
    "OXEYE_DAISY": "フランスギク",
    "CORNFLOWER": "ヤグルマギク",
    "LILY_OF_THE_VALLEY": "スズラン",
    "WITHER_ROSE": "ウィザーローズ",
    "SPORE_BLOSSOM": "胞子の花",
    "BROWN_MUSHROOM": "茶色のキノコ",
    "RED_MUSHROOM": "赤色のキノコ",
    "CRIMSON_FUNGUS": "真紅のキノコ",
    "WARPED_FUNGUS": "歪んだキノコ",
    "CRIMSON_ROOTS": "真紅の根",
    "WARPED_ROOTS": "歪んだ根",
    "NETHER_SPROUTS": "ネザースプラウト",
    "WEEPING_VINES": "しだれツタ",
    "TWISTING_VINES": "ねじれツタ",
    "SUGAR_CANE": "サトウキビ",
    "KELP": "コンブ",
    "MOSS_CARPET": "苔のカーペット",
    "MOSS_BLOCK": "苔ブロック",
    "HANGING_ROOTS": "垂れ根",
    "BIG_DRIPLEAF": "大きなドリップリーフ",
    "SMALL_DRIPLEAF": "小さなドリップリーフ",
    "BAMBOO": "竹",
    "OAK_SLAB": "オークのハーフブロック",
    "SPRUCE_SLAB": "トウヒのハーフブロック",
    "BIRCH_SLAB": "シラカバのハーフブロック",
    "JUNGLE_SLAB": "ジャングルのハーフブロック",
    "ACACIA_SLAB": "アカシアのハーフブロック",
    "DARK_OAK_SLAB": "ダークオークのハーフブロック",
    "CRIMSON_SLAB": "真紅のハーフブロック",
    "WARPED_SLAB": "歪んだハーフブロック",
    "STONE_SLAB": "石のハーフブロック",
    "SMOOTH_STONE_SLAB": "滑らかな石のハーフブロック",
    "SANDSTONE_SLAB": "砂岩のハーフブロック",
    "CUT_SANDSTONE_SLAB": "研がれた砂岩のハーフブロック",
    "PETRIFIED_OAK_SLAB": "石化したオークのハーフブロック",
    "COBBLESTONE_SLAB": "丸石のハーフブロック",
    "BRICK_SLAB": "レンガのハーフブロック",
    "STONE_BRICK_SLAB": "石レンガのハーフブロック",
    "NETHER_BRICK_SLAB": "ネザーレンガのハーフブロック",
    "QUARTZ_SLAB": "クォーツのハーフブロック",
    "RED_SANDSTONE_SLAB": "赤い砂岩のハーフブロック",
    "CUT_RED_SANDSTONE_SLAB": "研がれた赤い砂岩のハーフブロック",
    "PURPUR_SLAB": "プルプァのハーフブロック",
    "PRISMARINE_SLAB": "プリズマリンのハーフブロック",
    "PRISMARINE_BRICK_SLAB": "プリズマリンレンガのハーフブロック",
    "DARK_PRISMARINE_SLAB": "ダークプリズマリンのハーフブロック",
    "SMOOTH_QUARTZ": "滑らかなクォーツブロック",
    "SMOOTH_RED_SANDSTONE": "滑らかな赤い砂岩",
    "SMOOTH_SANDSTONE": "滑らかな砂岩",
    "SMOOTH_STONE": "滑らかな石",
    "BRICKS": "レンガ",
    "BOOKSHELF": "本棚",
    "MOSSY_COBBLESTONE": "苔むした丸石",
    "OBSIDIAN": "黒曜石",
    "TORCH": "松明",
    "END_ROD": "エンドロッド",
    "CHORUS_PLANT": "コーラスプラント",
    "CHORUS_FLOWER": "コーラスフラワー",
    "PURPUR_BLOCK": "プルプァブロック",
    "PURPUR_PILLAR": "プルプァの柱",
    "PURPUR_STAIRS": "プルプァの階段",
    "SPAWNER": "スポナー",
    "OAK_STAIRS": "オークの階段",
    "CHEST": "チェスト",
    "CRAFTING_TABLE": "作業台",
    "FARMLAND": "耕地",
    "FURNACE": "かまど",
    "LADDER": "はしご",
    "COBBLESTONE_STAIRS": "丸石の階段",
    "SNOW": "雪",
    "ICE": "氷",
    "SNOW_BLOCK": "雪ブロック",
    "CACTUS": "サボテン",
    "CLAY": "粘土",
    "JUKEBOX": "ジュークボックス",
    "OAK_FENCE": "オークのフェンス",
    "SPRUCE_FENCE": "トウヒのフェンス",
    "BIRCH_FENCE": "シラカバのフェンス",
    "JUNGLE_FENCE": "ジャングルのフェンス",
    "ACACIA_FENCE": "アカシアのフェンス",
    "DARK_OAK_FENCE": "ダークオークのフェンス",
    "CRIMSON_FENCE": "真紅のフェンス",
    "WARPED_FENCE": "歪んだフェンス",
    "PUMPKIN": "カボチャ",
    "CARVED_PUMPKIN": "くり抜かれたカボチャ",
    "JACK_O_LANTERN": "ジャック・オ・ランタン",
    "NETHERRACK": "ネザーラック",
    "SOUL_SAND": "ソウルサンド",
    "SOUL_SOIL": "ソウルソイル",
    "BASALT": "玄武岩",
    "POLISHED_BASALT": "磨かれた玄武岩",
    "SMOOTH_BASALT": "滑らかな玄武岩",
    "SOUL_TORCH": "魂の松明",
    "GLOWSTONE": "グロウストーン",
    "INFESTED_STONE": "虫食い石",
    "INFESTED_COBBLESTONE": "虫食い丸石",
    "INFESTED_STONE_BRICKS": "虫食い石レンガ",
    "INFESTED_MOSSY_STONE_BRICKS": "苔むした虫食い石レンガ",
    "INFESTED_CRACKED_STONE_BRICKS": "ひび割れた虫食い石レンガ",
    "INFESTED_CHISELED_STONE_BRICKS": "模様入りの虫食い石レンガ",
    "INFESTED_DEEPSLATE": "虫食い深層岩",
    "STONE_BRICKS": "石レンガ",
    "MOSSY_STONE_BRICKS": "苔むした石レンガ",
    "CRACKED_STONE_BRICKS": "ひび割れた石レンガ",
    "CHISELED_STONE_BRICKS": "模様入りの石レンガ",
    "DEEPSLATE_BRICKS": "深層岩レンガ",
    "CRACKED_DEEPSLATE_BRICKS": "ひび割れた深層岩レンガ",
    "DEEPSLATE_TILES": "深層岩タイル",
    "CRACKED_DEEPSLATE_TILES": "ひび割れた深層岩タイル",
    "CHISELED_DEEPSLATE": "模様入りの深層岩",
    "BROWN_MUSHROOM_BLOCK": "茶色のキノコブロック",
    "RED_MUSHROOM_BLOCK": "赤色のキノコブロック",
    "MUSHROOM_STEM": "キノコの柄",
    "IRON_BARS": "鉄格子",
    "CHAIN": "鎖",
    "GLASS_PANE": "ガラス板",
    "MELON": "スイカ",
    "VINE": "ツタ",
    "GLOW_LICHEN": "ヒカリゴケ",
    "BRICK_STAIRS": "レンガの階段",
    "STONE_BRICK_STAIRS": "石レンガの階段",
    "MYCELIUM": "菌糸",
    "LILY_PAD": "スイレンの葉",
    "NETHER_BRICKS": "ネザーレンガ",
    "CRACKED_NETHER_BRICKS": "ひび割れたネザーレンガ",
    "CHISELED_NETHER_BRICKS": "模様入りのネザーレンガ",
    "NETHER_BRICK_FENCE": "ネザーレンガのフェンス",
    "NETHER_BRICK_STAIRS": "ネザーレンガの階段",
    "ENCHANTING_TABLE": "エンチャントテーブル",
    "END_PORTAL_FRAME": "エンドポータルフレーム",
    "END_STONE": "エンドストーン",
    "END_STONE_BRICKS": "エンドストーンレンガ",
    "DRAGON_EGG": "ドラゴンの卵",
    "SANDSTONE_STAIRS": "砂岩の階段",
    "ENDER_CHEST": "エンダーチェスト",
    "EMERALD_BLOCK": "エメラルドブロック",
    "SPRUCE_STAIRS": "トウヒの階段",
    "BIRCH_STAIRS": "シラカバの階段",
    "JUNGLE_STAIRS": "ジャングルの階段",
    "CRIMSON_STAIRS": "真紅の階段",
    "WARPED_STAIRS": "歪んだ階段",
    "COMMAND_BLOCK": "コマンドブロック",
    "BEACON": "ビーコン",
    "COBBLESTONE_WALL": "丸石の塀",
    "MOSSY_COBBLESTONE_WALL": "苔むした丸石の塀",
    "BRICK_WALL": "レンガの塀",
    "PRISMARINE_WALL": "プリズマリンの塀",
    "RED_SANDSTONE_WALL": "赤い砂岩の塀",
    "MOSSY_STONE_BRICK_WALL": "苔むした石レンガの塀",
    "GRANITE_WALL": "花崗岩の塀",
    "STONE_BRICK_WALL": "石レンガの塀",
    "NETHER_BRICK_WALL": "ネザーレンガの塀",
    "ANDESITE_WALL": "安山岩の塀",
    "RED_NETHER_BRICK_WALL": "赤いネザーレンガの塀",
    "SANDSTONE_WALL": "砂岩の塀",
    "END_STONE_BRICK_WALL": "エンドストーンレンガの塀",
    "DIORITE_WALL": "閃緑岩の塀",
    "BLACKSTONE_WALL": "ブラックストーンの塀",
    "POLISHED_BLACKSTONE_WALL": "磨かれたブラックストーンの塀",
    "POLISHED_BLACKSTONE_BRICK_WALL": "磨かれたブラックストーンレンガの塀",
    "COBBLED_DEEPSLATE_WALL": "深層岩の丸石の塀",
    "POLISHED_DEEPSLATE_WALL": "磨かれた深層岩の塀",
    "DEEPSLATE_BRICK_WALL": "深層岩レンガの塀",
    "DEEPSLATE_TILE_WALL": "深層岩タイルの塀",
    "ANVIL": "金床",
    "CHIPPED_ANVIL": "欠けた金床",
    "DAMAGED_ANVIL": "壊れかけの金床",
    "CHISELED_QUARTZ_BLOCK": "模様入りのクォーツブロック",
    "QUARTZ_BLOCK": "クォーツブロック",
    "QUARTZ_BRICKS": "クォーツレンガ",
    "QUARTZ_PILLAR": "クォーツの柱",
    "QUARTZ_STAIRS": "クォーツの階段",
    "WHITE_TERRACOTTA": "白色のテラコッタ",
    "ORANGE_TERRACOTTA": "橙色のテラコッタ",
    "MAGENTA_TERRACOTTA": "赤紫色のテラコッタ",
    "LIGHT_BLUE_TERRACOTTA": "空色のテラコッタ",
    "YELLOW_TERRACOTTA": "黄色のテラコッタ",
    "LIME_TERRACOTTA": "黄緑色のテラコッタ",
    "PINK_TERRACOTTA": "桃色のテラコッタ",
    "GRAY_TERRACOTTA": "灰色のテラコッタ",
    "LIGHT_GRAY_TERRACOTTA": "薄灰色のテラコッタ",
    "CYAN_TERRACOTTA": "青緑色のテラコッタ",
    "PURPLE_TERRACOTTA": "紫色のテラコッタ",
    "BLUE_TERRACOTTA": "青色のテラコッタ",
    "BROWN_TERRACOTTA": "茶色のテラコッタ",
    "GREEN_TERRACOTTA": "緑色のテラコッタ",
    "RED_TERRACOTTA": "赤色のテラコッタ",
    "BLACK_TERRACOTTA": "黒色のテラコッタ",
    "BARRIER": "バリアブロック",
    "LIGHT": "ライトブロック",
    "HAY_BLOCK": "干草の俵",
    "WHITE_CARPET": "白色のカーペット",
    "ORANGE_CARPET": "橙色のカーペット",
    "MAGENTA_CARPET": "赤紫色のカーペット",
    "LIGHT_BLUE_CARPET": "空色のカーペット",
    "YELLOW_CARPET": "黄色のカーペット",
    "LIME_CARPET": "黄緑色のカーペット",
    "PINK_CARPET": "桃色のカーペット",
    "GRAY_CARPET": "灰色のカーペット",
    "LIGHT_GRAY_CARPET": "薄灰色のカーペット",
    "CYAN_CARPET": "青緑色のカーペット",
    "PURPLE_CARPET": "紫色のカーペット",
    "BLUE_CARPET": "青色のカーペット",
    "BROWN_CARPET": "茶色のカーペット",
    "GREEN_CARPET": "緑色のカーペット",
    "RED_CARPET": "赤色のカーペット",
    "BLACK_CARPET": "黒色のカーペット",
    "TERRACOTTA": "テラコッタ",
    "PACKED_ICE": "氷塊",
    "ACACIA_STAIRS": "アカシアの階段",
    "DARK_OAK_STAIRS": "ダークオークの階段",
    "DIRT_PATH": "土の道",
    "SUNFLOWER": "ヒマワリ",
    "LILAC": "ライラック",
    "ROSE_BUSH": "バラの低木",
    "PEONY": "ボタン",
    "TALL_GRASS": "背の高い草",
    "LARGE_FERN": "大きなシダ",
    "WHITE_STAINED_GLASS": "白色の色付きガラス",
    "ORANGE_STAINED_GLASS": "橙色の色付きガラス",
    "MAGENTA_STAINED_GLASS": "赤紫色の色付きガラス",
    "LIGHT_BLUE_STAINED_GLASS": "空色の色付きガラス",
    "YELLOW_STAINED_GLASS": "黄色の色付きガラス",
    "LIME_STAINED_GLASS": "黄緑色の色付きガラス",
    "PINK_STAINED_GLASS": "桃色の色付きガラス",
    "GRAY_STAINED_GLASS": "灰色の色付きガラス",
    "LIGHT_GRAY_STAINED_GLASS": "薄灰色の色付きガラス",
    "CYAN_STAINED_GLASS": "青緑色の色付きガラス",
    "PURPLE_STAINED_GLASS": "紫色の色付きガラス",
    "BLUE_STAINED_GLASS": "青色の色付きガラス",
    "BROWN_STAINED_GLASS": "茶色の色付きガラス",
    "GREEN_STAINED_GLASS": "緑色の色付きガラス",
    "RED_STAINED_GLASS": "赤色の色付きガラス",
    "BLACK_STAINED_GLASS": "黒色の色付きガラス",
    "WHITE_STAINED_GLASS_PANE": "白色の色付きガラス板",
    "ORANGE_STAINED_GLASS_PANE": "橙色の色付きガラス板",
    "MAGENTA_STAINED_GLASS_PANE": "赤紫色の色付きガラス板",
    "LIGHT_BLUE_STAINED_GLASS_PANE": "空色の色付きガラス板",
    "YELLOW_STAINED_GLASS_PANE": "黄色の色付きガラス板",
    "LIME_STAINED_GLASS_PANE": "黄緑色の色付きガラス板",
    "PINK_STAINED_GLASS_PANE": "桃色の色付きガラス板",
    "GRAY_STAINED_GLASS_PANE": "灰色の色付きガラス板",
    "LIGHT_GRAY_STAINED_GLASS_PANE": "薄灰色の色付きガラス板",
    "CYAN_STAINED_GLASS_PANE": "青緑色の色付きガラス板",
    "PURPLE_STAINED_GLASS_PANE": "紫色の色付きガラス板",
    "BLUE_STAINED_GLASS_PANE": "青色の色付きガラス板",
    "BROWN_STAINED_GLASS_PANE": "茶色の色付きガラス板",
    "GREEN_STAINED_GLASS_PANE": "緑色の色付きガラス板",
    "RED_STAINED_GLASS_PANE": "赤色の色付きガラス板",
    "BLACK_STAINED_GLASS_PANE": "黒色の色付きガラス板",
    "PRISMARINE": "プリズマリン",
    "PRISMARINE_BRICKS": "プリズマリンレンガ",
    "DARK_PRISMARINE": "ダークプリズマリン",
    "PRISMARINE_STAIRS": "プリズマリンの階段",
    "PRISMARINE_BRICK_STAIRS": "プリズマリンレンガの階段",
    "DARK_PRISMARINE_STAIRS": "ダークプリズマリンの階段",
    "SEA_LANTERN": "シーランタン",
    "RED_SANDSTONE": "赤い砂岩",
    "CHISELED_RED_SANDSTONE": "模様入りの赤い砂岩",
    "CUT_RED_SANDSTONE": "研がれた赤い砂岩",
    "RED_SANDSTONE_STAIRS": "赤い砂岩の階段",
    "REPEATING_COMMAND_BLOCK": "リピートコマンドブロック",
    "CHAIN_COMMAND_BLOCK": "チェーンコマンドブロック",
    "MAGMA_BLOCK": "マグマブロック",
    "NETHER_WART_BLOCK": "ネザーウォートブロック",
    "WARPED_WART_BLOCK": "歪んだウォートブロック",
    "RED_NETHER_BRICKS": "赤いネザーレンガ",
    "BONE_BLOCK": "骨ブロック",
    "STRUCTURE_VOID": "ストラクチャーヴォイド",
    "SHULKER_BOX": "シュルカーボックス",
    "WHITE_SHULKER_BOX": "白色のシュルカーボックス",
    "ORANGE_SHULKER_BOX": "橙色のシュルカーボックス",
    "MAGENTA_SHULKER_BOX": "赤紫色のシュルカーボックス",
    "LIGHT_BLUE_SHULKER_BOX": "空色のシュルカーボックス",
    "YELLOW_SHULKER_BOX": "黄色のシュルカーボックス",
    "LIME_SHULKER_BOX": "黄緑色のシュルカーボックス",
    "PINK_SHULKER_BOX": "桃色のシュルカーボックス",
    "GRAY_SHULKER_BOX": "灰色のシュルカーボックス",
    "LIGHT_GRAY_SHULKER_BOX": "薄灰色のシュルカーボックス",
    "CYAN_SHULKER_BOX": "青緑色のシュルカーボックス",
    "PURPLE_SHULKER_BOX": "紫色のシュルカーボックス",
    "BLUE_SHULKER_BOX": "青色のシュルカーボックス",
    "BROWN_SHULKER_BOX": "茶色のシュルカーボックス",
    "GREEN_SHULKER_BOX": "緑色のシュルカーボックス",
    "RED_SHULKER_BOX": "赤色のシュルカーボックス",
    "BLACK_SHULKER_BOX": "黒色のシュルカーボックス",
    "WHITE_GLAZED_TERRACOTTA": "白色の彩釉テラコッタ",
    "ORANGE_GLAZED_TERRACOTTA": "橙色の彩釉テラコッタ",
    "MAGENTA_GLAZED_TERRACOTTA": "赤紫色の彩釉テラコッタ",
    "LIGHT_BLUE_GLAZED_TERRACOTTA": "空色の彩釉テラコッタ",
    "YELLOW_GLAZED_TERRACOTTA": "黄色の彩釉テラコッタ",
    "LIME_GLAZED_TERRACOTTA": "黄緑色の彩釉テラコッタ",
    "PINK_GLAZED_TERRACOTTA": "桃色の彩釉テラコッタ",
    "GRAY_GLAZED_TERRACOTTA": "灰色の彩釉テラコッタ",
    "LIGHT_GRAY_GLAZED_TERRACOTTA": "薄灰色の彩釉テラコッタ",
    "CYAN_GLAZED_TERRACOTTA": "青緑色の彩釉テラコッタ",
    "PURPLE_GLAZED_TERRACOTTA": "紫色の彩釉テラコッタ",
    "BLUE_GLAZED_TERRACOTTA": "青色の彩釉テラコッタ",
    "BROWN_GLAZED_TERRACOTTA": "茶色の彩釉テラコッタ",
    "GREEN_GLAZED_TERRACOTTA": "緑色の彩釉テラコッタ",
    "RED_GLAZED_TERRACOTTA": "赤色の彩釉テラコッタ",
    "BLACK_GLAZED_TERRACOTTA": "黒色の彩釉テラコッタ",
    "WHITE_CONCRETE": "白色のコンクリート",
    "ORANGE_CONCRETE": "橙色のコンクリート",
    "MAGENTA_CONCRETE": "赤紫色のコンクリート",
    "LIGHT_BLUE_CONCRETE": "空色のコンクリート",
    "YELLOW_CONCRETE": "黄色のコンクリート",
    "LIME_CONCRETE": "黄緑色のコンクリート",
    "PINK_CONCRETE": "桃色のコンクリート",
    "GRAY_CONCRETE": "灰色のコンクリート",
    "LIGHT_GRAY_CONCRETE": "薄灰色のコンクリート",
    "CYAN_CONCRETE": "青緑色のコンクリート",
    "PURPLE_CONCRETE": "紫色のコンクリート",
    "BLUE_CONCRETE": "青色のコンクリート",
    "BROWN_CONCRETE": "茶色のコンクリート",
    "GREEN_CONCRETE": "緑色のコンクリート",
    "RED_CONCRETE": "赤色のコンクリート",
    "BLACK_CONCRETE": "黒色のコンクリート",
    "WHITE_CONCRETE_POWDER": "白色のコンクリートパウダー",
    "ORANGE_CONCRETE_POWDER": "橙色のコンクリートパウダー",
    "MAGENTA_CONCRETE_POWDER": "赤紫色のコンクリートパウダー",
    "LIGHT_BLUE_CONCRETE_POWDER": "空色のコンクリートパウダー",
    "YELLOW_CONCRETE_POWDER": "黄色のコンクリートパウダー",
    "LIME_CONCRETE_POWDER": "黄緑色のコンクリートパウダー",
    "PINK_CONCRETE_POWDER": "桃色のコンクリートパウダー",
    "GRAY_CONCRETE_POWDER": "灰色のコンクリートパウダー",
    "LIGHT_GRAY_CONCRETE_POWDER": "薄灰色のコンクリートパウダー",
    "CYAN_CONCRETE_POWDER": "青緑色のコンクリートパウダー",
    "PURPLE_CONCRETE_POWDER": "紫色のコンクリートパウダー",
    "BLUE_CONCRETE_POWDER": "青色のコンクリートパウダー",
    "BROWN_CONCRETE_POWDER": "茶色のコンクリートパウダー",
    "GREEN_CONCRETE_POWDER": "緑色のコンクリートパウダー",
    "RED_CONCRETE_POWDER": "赤色のコンクリートパウダー",
    "BLACK_CONCRETE_POWDER": "黒色のコンクリートパウダー",
    "TURTLE_EGG": "カメの卵",
    "DEAD_TUBE_CORAL_BLOCK": "死んだクダサンゴブロック",
    "DEAD_BRAIN_CORAL_BLOCK": "死んだノウサンゴブロック",
    "DEAD_BUBBLE_CORAL_BLOCK": "死んだミズタマサンゴブロック",
    "DEAD_FIRE_CORAL_BLOCK": "死んだミレポラサンゴブロック",
    "DEAD_HORN_CORAL_BLOCK": "死んだシカツノサンゴブロック",
    "TUBE_CORAL_BLOCK": "クダサンゴブロック",
    "BRAIN_CORAL_BLOCK": "ノウサンゴブロック",
    "BUBBLE_CORAL_BLOCK": "ミズタマサンゴブロック",
    "FIRE_CORAL_BLOCK": "ミレポラサンゴブロック",
    "HORN_CORAL_BLOCK": "シカツノサンゴブロック",
    "TUBE_CORAL": "クダサンゴ",
    "BRAIN_CORAL": "ノウサンゴ",
    "BUBBLE_CORAL": "ミズタマサンゴ",
    "FIRE_CORAL": "ミレポラサンゴ",
    "HORN_CORAL": "シカツノサンゴ",
    "DEAD_BRAIN_CORAL": "死んだノウサンゴ",
    "DEAD_BUBBLE_CORAL": "死んだミズタマサンゴ",
    "DEAD_FIRE_CORAL": "死んだミレポラサンゴ",
    "DEAD_HORN_CORAL": "死んだシカツノサンゴ",
    "DEAD_TUBE_CORAL": "死んだクダサンゴ",
    "TUBE_CORAL_FAN": "クダウチワサンゴ",
    "BRAIN_CORAL_FAN": "ノウウチワサンゴ",
    "BUBBLE_CORAL_FAN": "ミズタマウチワサンゴ",
    "FIRE_CORAL_FAN": "ミレポラウチワサンゴ",
    "HORN_CORAL_FAN": "シカツノウチワサンゴ",
    "DEAD_TUBE_CORAL_FAN": "死んだクダウチワサンゴ",
    "DEAD_BRAIN_CORAL_FAN": "死んだノウウチワサンゴ",
    "DEAD_BUBBLE_CORAL_FAN": "死んだミズタマウチワサンゴ",
    "DEAD_FIRE_CORAL_FAN": "死んだミレポラウチワサンゴ",
    "DEAD_HORN_CORAL_FAN": "死んだシカツノウチワサンゴ",
    "BLUE_ICE": "青氷",
    "CONDUIT": "コンジット",
    "POLISHED_GRANITE_STAIRS": "磨かれた花崗岩の階段",
    "SMOOTH_RED_SANDSTONE_STAIRS": "滑らかな赤い砂岩の階段",
    "MOSSY_STONE_BRICK_STAIRS": "苔むした石レンガの階段",
    "POLISHED_DIORITE_STAIRS": "磨かれた閃緑岩の階段",
    "MOSSY_COBBLESTONE_STAIRS": "苔むした丸石の階段",
    "END_STONE_BRICK_STAIRS": "エンドストーンレンガの階段",
    "STONE_STAIRS": "石の階段",
    "SMOOTH_SANDSTONE_STAIRS": "滑らかな砂岩の階段",
    "SMOOTH_QUARTZ_STAIRS": "滑らかなクォーツの階段",
    "GRANITE_STAIRS": "花崗岩の階段",
    "ANDESITE_STAIRS": "安山岩の階段",
    "RED_NETHER_BRICK_STAIRS": "赤いネザーレンガの階段",
    "POLISHED_ANDESITE_STAIRS": "磨かれた安山岩の階段",
    "DIORITE_STAIRS": "閃緑岩の階段",
    "COBBLED_DEEPSLATE_STAIRS": "深層岩の丸石の階段",
    "POLISHED_DEEPSLATE_STAIRS": "磨かれた深層岩の階段",
    "DEEPSLATE_BRICK_STAIRS": "深層岩レンガの階段",
    "DEEPSLATE_TILE_STAIRS": "深層岩タイルの階段",
    "POLISHED_GRANITE_SLAB": "磨かれた花崗岩のハーフブロック",
    "SMOOTH_RED_SANDSTONE_SLAB": "滑らかな赤い砂岩のハーフブロック",
    "MOSSY_STONE_BRICK_SLAB": "苔むした石レンガのハーフブロック",
    "POLISHED_DIORITE_SLAB": "磨かれた閃緑岩のハーフブロック",
    "MOSSY_COBBLESTONE_SLAB": "苔むした丸石のハーフブロック",
    "END_STONE_BRICK_SLAB": "エンドストーンレンガのハーフブロック",
    "SMOOTH_SANDSTONE_SLAB": "滑らかな砂岩のハーフブロック",
    "SMOOTH_QUARTZ_SLAB": "滑らかなクォーツのハーフブロック",
    "GRANITE_SLAB": "花崗岩のハーフブロック",
    "ANDESITE_SLAB": "安山岩のハーフブロック",
    "RED_NETHER_BRICK_SLAB": "赤いネザーレンガのハーフブロック",
    "POLISHED_ANDESITE_SLAB": "磨かれた安山岩のハーフブロック",
    "DIORITE_SLAB": "閃緑岩のハーフブロック",
    "COBBLED_DEEPSLATE_SLAB": "深層岩の丸石のハーフブロック",
    "POLISHED_DEEPSLATE_SLAB": "磨かれた深層岩のハーフブロック",
    "DEEPSLATE_BRICK_SLAB": "深層岩レンガのハーフブロック",
    "DEEPSLATE_TILE_SLAB": "深層岩タイルのハーフブロック",
    "SCAFFOLDING": "足場",
    "REDSTONE": "レッドストーンダスト",
    "REDSTONE_TORCH": "レッドストーントーチ",
    "REDSTONE_BLOCK": "レッドストーンブロック",
    "REPEATER": "レッドストーンリピーター",
    "COMPARATOR": "レッドストーンコンパレーター",
    "PISTON": "ピストン",
    "STICKY_PISTON": "粘着ピストン",
    "SLIME_BLOCK": "スライムブロック",
    "HONEY_BLOCK": "ハチミツブロック",
    "OBSERVER": "オブザーバー",
    "HOPPER": "ホッパー",
    "DISPENSER": "ディスペンサー",
    "DROPPER": "ドロッパー",
    "LECTERN": "書見台",
    "TARGET": "的",
    "LEVER": "レバー",
    "LIGHTNING_ROD": "避雷針",
    "DAYLIGHT_DETECTOR": "日照センサー",
    "SCULK_SENSOR": "スカルクセンサー",
    "TRIPWIRE_HOOK": "トリップワイヤーフック",
    "TRAPPED_CHEST": "トラップチェスト",
    "TNT": "TNT",
    "REDSTONE_LAMP": "レッドストーンランプ",
    "NOTE_BLOCK": "音符ブロック",
    "STONE_BUTTON": "石のボタン",
    "POLISHED_BLACKSTONE_BUTTON": "磨かれたブラックストーンのボタン",
    "OAK_BUTTON": "オークのボタン",
    "SPRUCE_BUTTON": "トウヒのボタン",
    "BIRCH_BUTTON": "シラカバのボタン",
    "JUNGLE_BUTTON": "ジャングルのボタン",
    "ACACIA_BUTTON": "アカシアのボタン",
    "DARK_OAK_BUTTON": "ダークオークのボタン",
    "CRIMSON_BUTTON": "真紅のボタン",
    "WARPED_BUTTON": "歪んだボタン",
    "STONE_PRESSURE_PLATE": "石の感圧板",
    "POLISHED_BLACKSTONE_PRESSURE_PLATE": "磨かれたブラックストーンの感圧板",
    "LIGHT_WEIGHTED_PRESSURE_PLATE": "軽量用感圧板",
    "HEAVY_WEIGHTED_PRESSURE_PLATE": "重量用感圧板",
    "OAK_PRESSURE_PLATE": "オークの感圧板",
    "SPRUCE_PRESSURE_PLATE": "トウヒの感圧板",
    "BIRCH_PRESSURE_PLATE": "シラカバの感圧板",
    "JUNGLE_PRESSURE_PLATE": "ジャングルの感圧板",
    "ACACIA_PRESSURE_PLATE": "アカシアの感圧板",
    "DARK_OAK_PRESSURE_PLATE": "ダークオークの感圧板",
    "CRIMSON_PRESSURE_PLATE": "真紅の感圧板",
    "WARPED_PRESSURE_PLATE": "歪んだ感圧板",
    "IRON_DOOR": "鉄のドア",
    "OAK_DOOR": "オークのドア",
    "SPRUCE_DOOR": "トウヒのドア",
    "BIRCH_DOOR": "シラカバのドア",
    "JUNGLE_DOOR": "ジャングルのドア",
    "ACACIA_DOOR": "アカシアのドア",
    "DARK_OAK_DOOR": "ダークオークのドア",
    "CRIMSON_DOOR": "真紅のドア",
    "WARPED_DOOR": "歪んだドア",
    "IRON_TRAPDOOR": "鉄のトラップドア",
    "OAK_TRAPDOOR": "オークのトラップドア",
    "SPRUCE_TRAPDOOR": "トウヒのトラップドア",
    "BIRCH_TRAPDOOR": "シラカバのトラップドア",
    "JUNGLE_TRAPDOOR": "ジャングルのトラップドア",
    "ACACIA_TRAPDOOR": "アカシアのトラップドア",
    "DARK_OAK_TRAPDOOR": "ダークオークのトラップドア",
    "CRIMSON_TRAPDOOR": "真紅のトラップドア",
    "WARPED_TRAPDOOR": "歪んだトラップドア",
    "OAK_FENCE_GATE": "オークのフェンスゲート",
    "SPRUCE_FENCE_GATE": "トウヒのフェンスゲート",
    "BIRCH_FENCE_GATE": "シラカバのフェンスゲート",
    "JUNGLE_FENCE_GATE": "ジャングルのフェンスゲート",
    "ACACIA_FENCE_GATE": "アカシアのフェンスゲート",
    "DARK_OAK_FENCE_GATE": "ダークオークのフェンスゲート",
    "CRIMSON_FENCE_GATE": "真紅のフェンスゲート",
    "WARPED_FENCE_GATE": "歪んだフェンスゲート",
    "POWERED_RAIL": "パワードレール",
    "DETECTOR_RAIL": "ディテクターレール",
    "RAIL": "レール",
    "ACTIVATOR_RAIL": "アクティベーターレール",
    "SADDLE": "鞍",
    "MINECART": "トロッコ",
    "CHEST_MINECART": "チェスト付きトロッコ",
    "FURNACE_MINECART": "かまど付きトロッコ",
    "TNT_MINECART": "TNT付きトロッコ",
    "HOPPER_MINECART": "ホッパー付きトロッコ",
    "CARROT_ON_A_STICK": "ニンジン付きの棒",
    "WARPED_FUNGUS_ON_A_STICK": "歪んだキノコ付きの棒",
    "ELYTRA": "エリトラ",
    "OAK_BOAT": "オークのボート",
    "SPRUCE_BOAT": "トウヒのボート",
    "BIRCH_BOAT": "シラカバのボート",
    "JUNGLE_BOAT": "ジャングルのボート",
    "ACACIA_BOAT": "アカシアのボート",
    "DARK_OAK_BOAT": "ダークオークのボート",
    "STRUCTURE_BLOCK": "ストラクチャーブロック",
    "JIGSAW": "ジグソーブロック",
    "TURTLE_HELMET": "カメの甲羅",
    "SCUTE": "カメのウロコ",
    "FLINT_AND_STEEL": "火打石と打ち金",
    "APPLE": "リンゴ",
    "BOW": "弓",
    "ARROW": "矢",
    "COAL": "石炭",
    "CHARCOAL": "木炭",
    "DIAMOND": "ダイヤモンド",
    "EMERALD": "エメラルド",
    "LAPIS_LAZULI": "ラピスラズリ",
    "QUARTZ": "ネザークォーツ",
    "AMETHYST_SHARD": "アメジストの欠片",
    "RAW_IRON": "鉄の原石",
    "IRON_INGOT": "鉄インゴット",
    "RAW_COPPER": "銅の原石",
    "COPPER_INGOT": "銅インゴット",
    "RAW_GOLD": "金の原石",
    "GOLD_INGOT": "金インゴット",
    "NETHERITE_INGOT": "ネザライトインゴット",
    "NETHERITE_SCRAP": "ネザライトの欠片",
    "WOODEN_SWORD": "木の剣",
    "WOODEN_SHOVEL": "木のシャベル",
    "WOODEN_PICKAXE": "木のツルハシ",
    "WOODEN_AXE": "木の斧",
    "WOODEN_HOE": "木のクワ",
    "STONE_SWORD": "石の剣",
    "STONE_SHOVEL": "石のシャベル",
    "STONE_PICKAXE": "石のツルハシ",
    "STONE_AXE": "石の斧",
    "STONE_HOE": "石のクワ",
    "GOLDEN_SWORD": "金の剣",
    "GOLDEN_SHOVEL": "金のシャベル",
    "GOLDEN_PICKAXE": "金のツルハシ",
    "GOLDEN_AXE": "金の斧",
    "GOLDEN_HOE": "金のクワ",
    "IRON_SWORD": "鉄の剣",
    "IRON_SHOVEL": "鉄のシャベル",
    "IRON_PICKAXE": "鉄のツルハシ",
    "IRON_AXE": "鉄の斧",
    "IRON_HOE": "鉄のクワ",
    "DIAMOND_SWORD": "ダイヤモンドの剣",
    "DIAMOND_SHOVEL": "ダイヤモンドのシャベル",
    "DIAMOND_PICKAXE": "ダイヤモンドのツルハシ",
    "DIAMOND_AXE": "ダイヤモンドの斧",
    "DIAMOND_HOE": "ダイヤモンドのクワ",
    "NETHERITE_SWORD": "ネザライトの剣",
    "NETHERITE_SHOVEL": "ネザライトのシャベル",
    "NETHERITE_PICKAXE": "ネザライトのツルハシ",
    "NETHERITE_AXE": "ネザライトの斧",
    "NETHERITE_HOE": "ネザライトのクワ",
    "STICK": "棒",
    "BOWL": "ボウル",
    "MUSHROOM_STEW": "キノコシチュー",
    "STRING": "糸",
    "FEATHER": "羽根",
    "GUNPOWDER": "火薬",
    "WHEAT_SEEDS": "小麦の種",
    "WHEAT": "小麦",
    "BREAD": "パン",
    "LEATHER_HELMET": "革の帽子",
    "LEATHER_CHESTPLATE": "革の上着",
    "LEATHER_LEGGINGS": "革のズボン",
    "LEATHER_BOOTS": "革のブーツ",
    "CHAINMAIL_HELMET": "チェーンのヘルメット",
    "CHAINMAIL_CHESTPLATE": "チェーンのチェストプレート",
    "CHAINMAIL_LEGGINGS": "チェーンのレギンス",
    "CHAINMAIL_BOOTS": "チェーンのブーツ",
    "IRON_HELMET": "鉄のヘルメット",
    "IRON_CHESTPLATE": "鉄のチェストプレート",
    "IRON_LEGGINGS": "鉄のレギンス",
    "IRON_BOOTS": "鉄のブーツ",
    "DIAMOND_HELMET": "ダイヤモンドのヘルメット",
    "DIAMOND_CHESTPLATE": "ダイヤモンドのチェストプレート",
    "DIAMOND_LEGGINGS": "ダイヤモンドのレギンス",
    "DIAMOND_BOOTS": "ダイヤモンドのブーツ",
    "GOLDEN_HELMET": "金のヘルメット",
    "GOLDEN_CHESTPLATE": "金のチェストプレート",
    "GOLDEN_LEGGINGS": "金のレギンス",
    "GOLDEN_BOOTS": "金のブーツ",
    "NETHERITE_HELMET": "ネザライトのヘルメット",
    "NETHERITE_CHESTPLATE": "ネザライトのチェストプレート",
    "NETHERITE_LEGGINGS": "ネザライトのレギンス",
    "NETHERITE_BOOTS": "ネザライトのブーツ",
    "FLINT": "火打石",
    "PORKCHOP": "生の豚肉",
    "COOKED_PORKCHOP": "焼き豚",
    "PAINTING": "絵画",
    "GOLDEN_APPLE": "金のリンゴ",
    "ENCHANTED_GOLDEN_APPLE": "エンチャントされた金のリンゴ",
    "OAK_SIGN": "オークの看板",
    "SPRUCE_SIGN": "トウヒの看板",
    "BIRCH_SIGN": "シラカバの看板",
    "JUNGLE_SIGN": "ジャングルの看板",
    "ACACIA_SIGN": "アカシアの看板",
    "DARK_OAK_SIGN": "ダークオークの看板",
    "CRIMSON_SIGN": "真紅の看板",
    "WARPED_SIGN": "歪んだ看板",
    "BUCKET": "バケツ",
    "WATER_BUCKET": "水入りバケツ",
    "LAVA_BUCKET": "溶岩入りバケツ",
    "POWDER_SNOW_BUCKET": "粉雪入りバケツ",
    "SNOWBALL": "雪玉",
    "LEATHER": "革",
    "MILK_BUCKET": "ミルク入りバケツ",
    "PUFFERFISH_BUCKET": "フグ入りバケツ",
    "SALMON_BUCKET": "サケ入りバケツ",
    "COD_BUCKET": "タラ入りバケツ",
    "TROPICAL_FISH_BUCKET": "熱帯魚入りバケツ",
    "AXOLOTL_BUCKET": "ウーパールーパー入りバケツ",
    "BRICK": "レンガ",
    "CLAY_BALL": "粘土玉",
    "DRIED_KELP_BLOCK": "乾燥した昆布ブロック",
    "PAPER": "紙",
    "BOOK": "本",
    "SLIME_BALL": "スライムボール",
    "EGG": "卵",
    "COMPASS": "コンパス",
    "BUNDLE": "バンドル",
    "FISHING_ROD": "釣竿",
    "CLOCK": "時計",
    "SPYGLASS": "望遠鏡",
    "GLOWSTONE_DUST": "グロウストーンダスト",
    "COD": "生鱈",
    "SALMON": "生鮭",
    "TROPICAL_FISH": "熱帯魚",
    "PUFFERFISH": "フグ",
    "COOKED_COD": "焼き鱈",
    "COOKED_SALMON": "焼き鮭",
    "INK_SAC": "イカスミ",
    "GLOW_INK_SAC": "輝くイカスミ",
    "COCOA_BEANS": "カカオ豆",
    "WHITE_DYE": "白色の染料",
    "ORANGE_DYE": "橙色の染料",
    "MAGENTA_DYE": "赤紫色の染料",
    "LIGHT_BLUE_DYE": "空色の染料",
    "YELLOW_DYE": "黄色の染料",
    "LIME_DYE": "黄緑色の染料",
    "PINK_DYE": "桃色の染料",
    "GRAY_DYE": "灰色の染料",
    "LIGHT_GRAY_DYE": "薄灰色の染料",
    "CYAN_DYE": "青緑色の染料",
    "PURPLE_DYE": "紫色の染料",
    "BLUE_DYE": "青色の染料",
    "BROWN_DYE": "茶色の染料",
    "GREEN_DYE": "緑色の染料",
    "RED_DYE": "赤色の染料",
    "BLACK_DYE": "黒色の染料",
    "BONE_MEAL": "骨粉",
    "BONE": "骨",
    "SUGAR": "砂糖",
    "CAKE": "ケーキ",
    "WHITE_BED": "白色のベッド",
    "ORANGE_BED": "橙色のベッド",
    "MAGENTA_BED": "赤紫色のベッド",
    "LIGHT_BLUE_BED": "空色のベッド",
    "YELLOW_BED": "黄色のベッド",
    "LIME_BED": "黄緑色のベッド",
    "PINK_BED": "桃色のベッド",
    "GRAY_BED": "灰色のベッド",
    "LIGHT_GRAY_BED": "薄灰色のベッド",
    "CYAN_BED": "青緑色のベッド",
    "PURPLE_BED": "紫色のベッド",
    "BLUE_BED": "青色のベッド",
    "BROWN_BED": "茶色のベッド",
    "GREEN_BED": "緑色のベッド",
    "RED_BED": "赤色のベッド",
    "BLACK_BED": "黒色のベッド",
    "COOKIE": "クッキー",
    "FILLED_MAP": "地図",
    "SHEARS": "ハサミ",
    "MELON_SLICE": "スイカの薄切り",
    "DRIED_KELP": "乾燥した昆布",
    "PUMPKIN_SEEDS": "カボチャの種",
    "MELON_SEEDS": "スイカの種",
    "BEEF": "生の牛肉",
    "COOKED_BEEF": "ステーキ",
    "CHICKEN": "生の鶏肉",
    "COOKED_CHICKEN": "焼き鳥",
    "ROTTEN_FLESH": "腐った肉",
    "ENDER_PEARL": "エンダーパール",
    "BLAZE_ROD": "ブレイズロッド",
    "GHAST_TEAR": "ガストの涙",
    "GOLD_NUGGET": "金塊",
    "NETHER_WART": "ネザーウォート",
    "POTION": "ポーション",
    "GLASS_BOTTLE": "ガラス瓶",
    "SPIDER_EYE": "クモの目",
    "FERMENTED_SPIDER_EYE": "発酵したクモの目",
    "BLAZE_POWDER": "ブレイズパウダー",
    "MAGMA_CREAM": "マグマクリーム",
    "BREWING_STAND": "醸造台",
    "CAULDRON": "大釜",
    "ENDER_EYE": "エンダーアイ",
    "GLISTERING_MELON_SLICE": "きらめくスイカの薄切り",
    "AXOLOTL_SPAWN_EGG": "ウーパールーパーのスポーンエッグ",
    "BAT_SPAWN_EGG": "コウモリのスポーンエッグ",
    "BEE_SPAWN_EGG": "ミツバチのスポーンエッグ",
    "BLAZE_SPAWN_EGG": "ブレイズのスポーンエッグ",
    "CAT_SPAWN_EGG": "ネコのスポーンエッグ",
    "CAVE_SPIDER_SPAWN_EGG": "洞窟グモのスポーンエッグ",
    "CHICKEN_SPAWN_EGG": "ニワトリのスポーンエッグ",
    "COD_SPAWN_EGG": "タラのスポーンエッグ",
    "COW_SPAWN_EGG": "ウシのスポーンエッグ",
    "CREEPER_SPAWN_EGG": "クリーパーのスポーンエッグ",
    "DOLPHIN_SPAWN_EGG": "イルカのスポーンエッグ",
    "DONKEY_SPAWN_EGG": "ロバのスポーンエッグ",
    "DROWNED_SPAWN_EGG": "ドラウンドのスポーンエッグ",
    "ELDER_GUARDIAN_SPAWN_EGG": "エルダーガーディアンのスポーンエッグ",
    "ENDERMAN_SPAWN_EGG": "エンダーマンのスポーンエッグ",
    "ENDERMITE_SPAWN_EGG": "エンダーマイトのスポーンエッグ",
    "EVOKER_SPAWN_EGG": "エヴォーカーのスポーンエッグ",
    "FOX_SPAWN_EGG": "キツネのスポーンエッグ",
    "GHAST_SPAWN_EGG": "ガストのスポーンエッグ",
    "GLOW_SQUID_SPAWN_EGG": "ヒカリイカのスポーンエッグ",
    "GOAT_SPAWN_EGG": "ヤギのスポーンエッグ",
    "GUARDIAN_SPAWN_EGG": "ガーディアンのスポーンエッグ",
    "HOGLIN_SPAWN_EGG": "ホグリンのスポーンエッグ",
    "HORSE_SPAWN_EGG": "ウマのスポーンエッグ",
    "HUSK_SPAWN_EGG": "ハスクのスポーンエッグ",
    "LLAMA_SPAWN_EGG": "ラマのスポーンエッグ",
    "MAGMA_CUBE_SPAWN_EGG": "マグマキューブのスポーンエッグ",
    "MOOSHROOM_SPAWN_EGG": "ムーシュルームのスポーンエッグ",
    "MULE_SPAWN_EGG": "ラバのスポーンエッグ",
    "OCELOT_SPAWN_EGG": "ヤマネコのスポーンエッグ",
    "PANDA_SPAWN_EGG": "パンダのスポーンエッグ",
    "PARROT_SPAWN_EGG": "オウムのスポーンエッグ",
    "PHANTOM_SPAWN_EGG": "ファントムのスポーンエッグ",
    "PIG_SPAWN_EGG": "ブタのスポーンエッグ",
    "PIGLIN_SPAWN_EGG": "ピグリンのスポーンエッグ",
    "PIGLIN_BRUTE_SPAWN_EGG": "ピグリンブルートのスポーンエッグ",
    "PILLAGER_SPAWN_EGG": "ピリジャーのスポーンエッグ",
    "POLAR_BEAR_SPAWN_EGG": "シロクマのスポーンエッグ",
    "PUFFERFISH_SPAWN_EGG": "フグのスポーンエッグ",
    "RABBIT_SPAWN_EGG": "ウサギのスポーンエッグ",
    "RAVAGER_SPAWN_EGG": "ラヴェジャーのスポーンエッグ",
    "SALMON_SPAWN_EGG": "サケのスポーンエッグ",
    "SHEEP_SPAWN_EGG": "ヒツジのスポーンエッグ",
    "SHULKER_SPAWN_EGG": "シュルカーのスポーンエッグ",
    "SILVERFISH_SPAWN_EGG": "シルバーフィッシュのスポーンエッグ",
    "SKELETON_SPAWN_EGG": "スケルトンのスポーンエッグ",
    "SKELETON_HORSE_SPAWN_EGG": "スケルトンホースのスポーンエッグ",
    "SLIME_SPAWN_EGG": "スライムのスポーンエッグ",
    "SPIDER_SPAWN_EGG": "クモのスポーンエッグ",
    "SQUID_SPAWN_EGG": "イカのスポーンエッグ",
    "STRAY_SPAWN_EGG": "ストレイのスポーンエッグ",
    "STRIDER_SPAWN_EGG": "ストライダーのスポーンエッグ",
    "TRADER_LLAMA_SPAWN_EGG": "商人のラマのスポーンエッグ",
    "TROPICAL_FISH_SPAWN_EGG": "熱帯魚のスポーンエッグ",
    "TURTLE_SPAWN_EGG": "カメのスポーンエッグ",
    "VEX_SPAWN_EGG": "ヴェックスのスポーンエッグ",
    "VILLAGER_SPAWN_EGG": "村人のスポーンエッグ",
    "VINDICATOR_SPAWN_EGG": "ヴィンディケーターのスポーンエッグ",
    "WANDERING_TRADER_SPAWN_EGG": "行商人のスポーンエッグ",
    "WITCH_SPAWN_EGG": "ウィッチのスポーンエッグ",
    "WITHER_SKELETON_SPAWN_EGG": "ウィザースケルトンのスポーンエッグ",
    "WOLF_SPAWN_EGG": "オオカミのスポーンエッグ",
    "ZOGLIN_SPAWN_EGG": "ゾグリンのスポーンエッグ",
    "ZOMBIE_SPAWN_EGG": "ゾンビのスポーンエッグ",
    "ZOMBIE_HORSE_SPAWN_EGG": "ゾンビホースのスポーンエッグ",
    "ZOMBIE_VILLAGER_SPAWN_EGG": "村人ゾンビのスポーンエッグ",
    "ZOMBIFIED_PIGLIN_SPAWN_EGG": "ゾンビピグリンのスポーンエッグ",
    "EXPERIENCE_BOTTLE": "エンチャントの瓶",
    "FIRE_CHARGE": "ファイヤーチャージ",
    "WRITABLE_BOOK": "本と羽根ペン",
    "WRITTEN_BOOK": "記入済みの本",
    "ITEM_FRAME": "額縁",
    "GLOW_ITEM_FRAME": "輝く額縁",
    "FLOWER_POT": "植木鉢",
    "CARROT": "ニンジン",
    "POTATO": "ジャガイモ",
    "BAKED_POTATO": "ベイクドポテト",
    "POISONOUS_POTATO": "青くなったジャガイモ",
    "MAP": "白紙の地図",
    "GOLDEN_CARROT": "金のニンジン",
    "SKELETON_SKULL": "スケルトンの頭蓋骨",
    "WITHER_SKELETON_SKULL": "ウィザースケルトンの頭蓋骨",
    "PLAYER_HEAD": "プレイヤーの頭",
    "ZOMBIE_HEAD": "ゾンビの頭",
    "CREEPER_HEAD": "クリーパーの頭",
    "DRAGON_HEAD": "ドラゴンの頭",
    "NETHER_STAR": "ネザースター",
    "PUMPKIN_PIE": "パンプキンパイ",
    "FIREWORK_ROCKET": "ロケット花火",
    "FIREWORK_STAR": "花火の星",
    "ENCHANTED_BOOK": "エンチャントの本",
    "NETHER_BRICK": "ネザーレンガ",
    "PRISMARINE_SHARD": "プリズマリンの欠片",
    "PRISMARINE_CRYSTALS": "プリズマリンクリスタル",
    "RABBIT": "生の兎肉",
    "COOKED_RABBIT": "焼き兎肉",
    "RABBIT_STEW": "ウサギシチュー",
    "RABBIT_FOOT": "ウサギの足",
    "RABBIT_HIDE": "ウサギの皮",
    "ARMOR_STAND": "防具立て",
    "IRON_HORSE_ARMOR": "鉄の馬鎧",
    "GOLDEN_HORSE_ARMOR": "金の馬鎧",
    "DIAMOND_HORSE_ARMOR": "ダイヤモンドの馬鎧",
    "LEATHER_HORSE_ARMOR": "革の馬鎧",
    "LEAD": "リード",
    "NAME_TAG": "名札",
    "COMMAND_BLOCK_MINECART": "コマンドブロック付きトロッコ",
    "MUTTON": "生の羊肉",
    "COOKED_MUTTON": "焼き羊肉",
    "WHITE_BANNER": "白色の旗",
    "ORANGE_BANNER": "橙色の旗",
    "MAGENTA_BANNER": "赤紫色の旗",
    "LIGHT_BLUE_BANNER": "空色の旗",
    "YELLOW_BANNER": "黄色の旗",
    "LIME_BANNER": "黄緑色の旗",
    "PINK_BANNER": "桃色の旗",
    "GRAY_BANNER": "灰色の旗",
    "LIGHT_GRAY_BANNER": "薄灰色の旗",
    "CYAN_BANNER": "青緑色の旗",
    "PURPLE_BANNER": "紫色の旗",
    "BLUE_BANNER": "青色の旗",
    "BROWN_BANNER": "茶色の旗",
    "GREEN_BANNER": "緑色の旗",
    "RED_BANNER": "赤色の旗",
    "BLACK_BANNER": "黒色の旗",
    "END_CRYSTAL": "エンドクリスタル",
    "CHORUS_FRUIT": "コーラスフルーツ",
    "POPPED_CHORUS_FRUIT": "焼いたコーラスフルーツ",
    "BEETROOT": "ビートルート",
    "BEETROOT_SEEDS": "ビートルートの種",
    "BEETROOT_SOUP": "ビートルートスープ",
    "DRAGON_BREATH": "ドラゴンブレス",
    "SPLASH_POTION": "スプラッシュポーション",
    "SPECTRAL_ARROW": "光の矢",
    "TIPPED_ARROW": "効能付きの矢",
    "LINGERING_POTION": "残留ポーション",
    "SHIELD": "盾",
    "TOTEM_OF_UNDYING": "不死のトーテム",
    "SHULKER_SHELL": "シュルカーの殻",
    "IRON_NUGGET": "鉄塊",
    "KNOWLEDGE_BOOK": "知恵の本",
    "DEBUG_STICK": "デバッグ棒",
    "MUSIC_DISC_13": "レコード",
    "MUSIC_DISC_CAT": "レコード",
    "MUSIC_DISC_BLOCKS": "レコード",
    "MUSIC_DISC_CHIRP": "レコード",
    "MUSIC_DISC_FAR": "レコード",
    "MUSIC_DISC_MALL": "レコード",
    "MUSIC_DISC_MELLOHI": "レコード",
    "MUSIC_DISC_STAL": "レコード",
    "MUSIC_DISC_STRAD": "レコード",
    "MUSIC_DISC_WARD": "レコード",
    "MUSIC_DISC_11": "レコード",
    "MUSIC_DISC_WAIT": "レコード",
    "MUSIC_DISC_PIGSTEP": "レコード",
    "TRIDENT": "トライデント",
    "PHANTOM_MEMBRANE": "ファントムの皮膜",
    "NAUTILUS_SHELL": "オウムガイの殻",
    "HEART_OF_THE_SEA": "海洋の心",
    "CROSSBOW": "クロスボウ",
    "SUSPICIOUS_STEW": "怪しげなシチュー",
    "LOOM": "機織り機",
    "FLOWER_BANNER_PATTERN": "旗の模様",
    "CREEPER_BANNER_PATTERN": "旗の模様",
    "SKULL_BANNER_PATTERN": "旗の模様",
    "MOJANG_BANNER_PATTERN": "旗の模様",
    "GLOBE_BANNER_PATTERN": "旗の模様",
    "PIGLIN_BANNER_PATTERN": "旗の模様",
    "COMPOSTER": "コンポスター",
    "BARREL": "樽",
    "SMOKER": "燻製器",
    "BLAST_FURNACE": "溶鉱炉",
    "CARTOGRAPHY_TABLE": "製図台",
    "FLETCHING_TABLE": "矢細工台",
    "GRINDSTONE": "砥石",
    "SMITHING_TABLE": "鍛冶台",
    "STONECUTTER": "石切台",
    "BELL": "鐘",
    "LANTERN": "ランタン",
    "SOUL_LANTERN": "魂のランタン",
    "SWEET_BERRIES": "スイートベリー",
    "GLOW_BERRIES": "グロウベリー",
    "CAMPFIRE": "焚き火",
    "SOUL_CAMPFIRE": "魂の焚き火",
    "SHROOMLIGHT": "シュルームライト",
    "HONEYCOMB": "ハニカム",
    "BEE_NEST": "ミツバチの巣",
    "BEEHIVE": "養蜂箱",
    "HONEY_BOTTLE": "ハチミツ入りの瓶",
    "HONEYCOMB_BLOCK": "ハニカムブロック",
    "LODESTONE": "ロードストーン",
    "CRYING_OBSIDIAN": "泣く黒曜石",
    "BLACKSTONE": "ブラックストーン",
    "BLACKSTONE_SLAB": "ブラックストーンのハーフブロック",
    "BLACKSTONE_STAIRS": "ブラックストーンの階段",
    "GILDED_BLACKSTONE": "きらめくブラックストーン",
    "POLISHED_BLACKSTONE": "磨かれたブラックストーン",
    "POLISHED_BLACKSTONE_SLAB": "磨かれたブラックストーンのハーフブロック",
    "POLISHED_BLACKSTONE_STAIRS": "磨かれたブラックストーンの階段",
    "CHISELED_POLISHED_BLACKSTONE": "模様入りの磨かれたブラックストーン",
    "POLISHED_BLACKSTONE_BRICKS": "磨かれたブラックストーンレンガ",
    "POLISHED_BLACKSTONE_BRICK_SLAB": "磨かれたブラックストーンレンガのハーフブロック",
    "POLISHED_BLACKSTONE_BRICK_STAIRS": "磨かれたブラックストーンレンガの階段",
    "CRACKED_POLISHED_BLACKSTONE_BRICKS": "ひび割れたブラックストーンレンガ",
    "RESPAWN_ANCHOR": "リスポーンアンカー",
    "CANDLE": "ろうそく",
    "WHITE_CANDLE": "白色のろうそく",
    "ORANGE_CANDLE": "橙色のろうそく",
    "MAGENTA_CANDLE": "赤紫色のろうそく",
    "LIGHT_BLUE_CANDLE": "空色のろうそく",
    "YELLOW_CANDLE": "黄色のろうそく",
    "LIME_CANDLE": "黄緑色のろうそく",
    "PINK_CANDLE": "桃色のろうそく",
    "GRAY_CANDLE": "灰色のろうそく",
    "LIGHT_GRAY_CANDLE": "薄灰色のろうそく",
    "CYAN_CANDLE": "青緑色のろうそく",
    "PURPLE_CANDLE": "紫色のろうそく",
    "BLUE_CANDLE": "青色のろうそく",
    "BROWN_CANDLE": "茶色のろうそく",
    "GREEN_CANDLE": "緑色のろうそく",
    "RED_CANDLE": "赤色のろうそく",
    "BLACK_CANDLE": "黒色のろうそく",
    "SMALL_AMETHYST_BUD": "小さなアメジストの芽",
    "MEDIUM_AMETHYST_BUD": "中くらいのアメジストの芽",
    "LARGE_AMETHYST_BUD": "大きなアメジストの芽",
    "AMETHYST_CLUSTER": "アメジストの塊",
    "POINTED_DRIPSTONE": "鍾乳石",
    "WATER": "水",
    "LAVA": "溶岩",
    "TALL_SEAGRASS": "背の高い海草",
    "PISTON_HEAD": "ピストンヘッド",
    "MOVING_PISTON": "作動中のピストン",
    "WALL_TORCH": "壁に付けられた松明",
    "FIRE": "炎",
    "SOUL_FIRE": "魂の炎",
    "REDSTONE_WIRE": "レッドストーンワイヤー",
    "OAK_WALL_SIGN": "壁に付けられたオークの看板",
    "SPRUCE_WALL_SIGN": "壁に付けられたトウヒの看板",
    "BIRCH_WALL_SIGN": "壁に付けられたシラカバの看板",
    "ACACIA_WALL_SIGN": "壁に付けられたアカシアの看板",
    "JUNGLE_WALL_SIGN": "壁に付けられたジャングルの看板",
    "DARK_OAK_WALL_SIGN": "壁に付けられたダークオークの看板",
    "REDSTONE_WALL_TORCH": "壁に付けられたレッドストーントーチ",
    "SOUL_WALL_TORCH": "壁に付けられた魂の松明",
    "NETHER_PORTAL": "ネザーポータル",
    "ATTACHED_PUMPKIN_STEM": "実がなったカボチャの茎",
    "ATTACHED_MELON_STEM": "実がなったスイカの茎",
    "PUMPKIN_STEM": "カボチャの茎",
    "MELON_STEM": "スイカの茎",
    "WATER_CAULDRON": "水入りの大釜",
    "LAVA_CAULDRON": "溶岩入りの大釜",
    "POWDER_SNOW_CAULDRON": "粉雪入りの大釜",
    "END_PORTAL": "エンドポータル",
    "COCOA": "カカオの実",
    "TRIPWIRE": "トリップワイヤー",
    "POTTED_OAK_SAPLING": "植えられたオークの苗木",
    "POTTED_SPRUCE_SAPLING": "植えられたトウヒの苗木",
    "POTTED_BIRCH_SAPLING": "植えられたシラカバの苗木",
    "POTTED_JUNGLE_SAPLING": "植えられたジャングルの苗木",
    "POTTED_ACACIA_SAPLING": "植えられたアカシアの苗木",
    "POTTED_DARK_OAK_SAPLING": "植えられたダークオークの苗木",
    "POTTED_FERN": "植えられたシダ",
    "POTTED_DANDELION": "植えられたタンポポ",
    "POTTED_POPPY": "植えられたポピー",
    "POTTED_BLUE_ORCHID": "植えられたヒスイラン",
    "POTTED_ALLIUM": "植えられたアリウム",
    "POTTED_AZURE_BLUET": "植えられたヒナソウ",
    "POTTED_RED_TULIP": "植えられた赤色のチューリップ",
    "POTTED_ORANGE_TULIP": "植えられた橙色のチューリップ",
    "POTTED_WHITE_TULIP": "植えられた白色のチューリップ",
    "POTTED_PINK_TULIP": "植えられた桃色のチューリップ",
    "POTTED_OXEYE_DAISY": "植えられたフランスギク",
    "POTTED_CORNFLOWER": "植えられたヤグルマギク",
    "POTTED_LILY_OF_THE_VALLEY": "植えられたスズラン",
    "POTTED_WITHER_ROSE": "植えられたウィザーローズ",
    "POTTED_RED_MUSHROOM": "植えられた赤色のキノコ",
    "POTTED_BROWN_MUSHROOM": "植えられた茶色のキノコ",
    "POTTED_DEAD_BUSH": "植えられた枯れ木",
    "POTTED_CACTUS": "植えられたサボテン",
    "CARROTS": "ニンジン",
    "POTATOES": "ジャガイモ",
    "SKELETON_WALL_SKULL": "壁に付けられたスケルトンの頭蓋骨",
    "WITHER_SKELETON_WALL_SKULL": "壁に付けられたウィザースケルトンの頭蓋骨",
    "ZOMBIE_WALL_HEAD": "壁に付けられたゾンビの頭",
    "PLAYER_WALL_HEAD": "壁に付けられたプレイヤーの頭",
    "CREEPER_WALL_HEAD": "壁に付けられたクリーパーの頭",
    "DRAGON_WALL_HEAD": "壁に付けられたドラゴンの頭",
    "BEETROOTS": "ビートルート",
    "END_GATEWAY": "エンドゲートウェイ",
    "FROSTED_ICE": "薄氷",
    "KELP_PLANT": "コンブの茎",
    "DEAD_TUBE_CORAL_WALL_FAN": "壁付きの死んだクダウチワサンゴ",
    "DEAD_BRAIN_CORAL_WALL_FAN": "壁付きの死んだノウウチワサンゴ",
    "DEAD_BUBBLE_CORAL_WALL_FAN": "壁付きの死んだミズタマウチワサンゴ",
    "DEAD_FIRE_CORAL_WALL_FAN": "壁付きの死んだミレポラウチワサンゴ",
    "DEAD_HORN_CORAL_WALL_FAN": "壁付きの死んだシカツノウチワサンゴ",
    "TUBE_CORAL_WALL_FAN": "壁付きのクダウチワサンゴ",
    "BRAIN_CORAL_WALL_FAN": "壁付きのノウウチワサンゴ",
    "BUBBLE_CORAL_WALL_FAN": "壁付きのミズタマウチワサンゴ",
    "FIRE_CORAL_WALL_FAN": "壁付きのミレポラウチワサンゴ",
    "HORN_CORAL_WALL_FAN": "壁付きのシカツノウチワサンゴ",
    "BAMBOO_SAPLING": "タケノコ",
    "POTTED_BAMBOO": "植えられた竹",
    "VOID_AIR": "奈落の空気",
    "CAVE_AIR": "洞窟の空気",
    "BUBBLE_COLUMN": "気泡柱",
    "SWEET_BERRY_BUSH": "スイートベリーの低木",
    "WEEPING_VINES_PLANT": "しだれツタのつる",
    "TWISTING_VINES_PLANT": "ねじれツタのつる",
    "CRIMSON_WALL_SIGN": "壁に付けられた真紅の看板",
    "WARPED_WALL_SIGN": "壁に付けられた歪んだ看板",
    "POTTED_CRIMSON_FUNGUS": "植えられた真紅のキノコ",
    "POTTED_WARPED_FUNGUS": "植えられた歪んだキノコ",
    "POTTED_CRIMSON_ROOTS": "植えられた真紅の根",
    "POTTED_WARPED_ROOTS": "植えられた歪んだ根",
    "CANDLE_CAKE": "ろうそくが立てられたケーキ",
    "WHITE_CANDLE_CAKE": "白色のろうそく付きケーキ",
    "ORANGE_CANDLE_CAKE": "橙色のろうそく付きケーキ",
    "MAGENTA_CANDLE_CAKE": "赤紫色のろうそく付きケーキ",
    "LIGHT_BLUE_CANDLE_CAKE": "空色のろうそく付きケーキ",
    "YELLOW_CANDLE_CAKE": "黄色のろうそく付きケーキ",
    "LIME_CANDLE_CAKE": "黄緑色のろうそく付きケーキ",
    "PINK_CANDLE_CAKE": "桃色のろうそく付きケーキ",
    "GRAY_CANDLE_CAKE": "灰色のろうそく付きケーキ",
    "LIGHT_GRAY_CANDLE_CAKE": "薄灰色のろうそく付きケーキ",
    "CYAN_CANDLE_CAKE": "青緑色のろうそく付きケーキ",
    "PURPLE_CANDLE_CAKE": "紫色のろうそく付きケーキ",
    "BLUE_CANDLE_CAKE": "青色のろうそく付きケーキ",
    "BROWN_CANDLE_CAKE": "茶色のろうそく付きケーキ",
    "GREEN_CANDLE_CAKE": "緑色のろうそく付きケーキ",
    "RED_CANDLE_CAKE": "赤色のろうそく付きケーキ",
    "BLACK_CANDLE_CAKE": "黒色のろうそく付きケーキ",
    "POWDER_SNOW": "粉雪",
    "CAVE_VINES": "洞窟のツタ",
    "CAVE_VINES_PLANT": "洞窟のツタのつる",
    "BIG_DRIPLEAF_STEM": "大きなドリップリーフの茎",
    "POTTED_AZALEA_BUSH": "植えられたツツジ",
    "POTTED_FLOWERING_AZALEA_BUSH": "植えられた開花したツツジ"
};
